version: "3"
services:
  # User microservice db - - - - - - - -
  juna-user-db:
    image: mongo:latest
    container_name: juna-user-db
    ports:
      - "4000:27017"
    restart: always

  # User microservice - - - - - - - -
  juna-user:
    image: juna-user
    build:
      context: ./user
      dockerfile: Dockerfile-dev
    env_file:
      - ./user/.env

    volumes:
      - /tmp/user/npm-cache:/root/.npm:z
      - ./user/src:/usr/src/app/src:z

    container_name: juna-user
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - USER_DBHOST=mongodb://juna-user-db:27017
      - USER_DBNAME=juna-user-db
      - LN_API_BASE=http://juna-lightning:80

    depends_on:
      - juna-user-db

    restart: "no"

  # Lightning microservice - - - - - - - -
  juna-lightning:
    image: juna-lightning
    build:
      context: ./lightning
      dockerfile: Dockerfile-dev

    volumes:
      - /tmp/lightning/npm-cache:/root/.npm:z
      - ./lightning/src:/usr/src/app/src:z

    container_name: juna-lightning
    ports:
      - "4002:80"
    environment:
      - PORT=80
    env_file:
      - ./lightning/.env

    restart: "no"
