version: "3"
services:
  # Auth microservice db - - - - - - - -
  # vaus-auth-db:
  #   image: mongo:latest
  #   container_name: vaus-auth-db
  #   ports:
  #     - "4000:27017"
  #   restart: always

  # Auth microservice - - - - - - - -
  # vaus-auth:
  #   image: vaus-auth
  #   build:
  #     context: ./auth
  #     dockerfile: Dockerfile-dev
  #   env_file:
  #     - .env

  #   volumes:
  #     - /tmp/auth/npm-cache:/root/.npm:z
  #     - ./auth/src:/usr/src/app/src:z

  #   container_name: vaus-auth
  #   ports:
  #     - "4001:80"
  #   environment:
  #     - PORT=80
  #     - AUTH_DBHOST=mongodb://vaus-auth-db:27017
  #     - AUTH_DBNAME=vaus-auth-db

  #   depends_on:
  #     - vaus-auth-db

  #   restart: "no"

  # Video microservice database - - - - - - - -
  vaus-video-db:
    image: mongo:latest
    container_name: vaus-video-db
    ports:
      - "4002:27017"
    restart: always

  # Video microservice - - - - - - - -
  vaus-video:
    image: vaus-video
    build:
      context: ./video
      dockerfile: Dockerfile-dev
    env_file:
      - .env

    volumes:
      - /tmp/video/npm-cache:/root/.npm:z
      - ./video/src:/usr/src/app/src:z

    container_name: vaus-video
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - VIDEO_DBHOST=mongodb://vaus-video-db:27017
      - VIDEO_DBNAME=vaus-video-db
      - RABBIT=amqp://guest:guest@rabbit:5672

    depends_on:
      - vaus-video-db

    restart: "no"

  # History microservice database - - - - - - - -
  vaus-history-db:
    image: mongo:latest
    container_name: vaus-history-db
    ports:
      - "4004:27017"
    restart: always

  # History microservice - - - - - - - -
  vaus-history:
    image: vaus-history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z

    container_name: vaus-history
    ports:
      - "4005:80"
    environment:
      - PORT=80
      - HISTORY_DBHOST=mongodb://vaus-history-db:27017
      - HISTORY_DBNAME=vaus-history-db
      - RABBIT=amqp://guest:guest@rabbit:5672

    restart: "no"

  # RabbitMQ - - - - - - - -
  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit

    ports:
      - "5672:5672"
      - "15672:15672"

    expose:
      - "5672"
      - "15672"

    restart: "always"

  # Frontend React Client - - - - - - - -
  # vaus-client:
  #   image: vaus-client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   env_file: ./client/.env

  #   container_name: vaus-client
  #   ports:
  #     - "4006:3000"
  #   environment:
  #     - REACT_APP_VIDEO_API_BASE_URL=http://localhost:4003/api/v1
  #     - REACT_APP_CLOUDINARY_ENDPOINT=https://api.cloudinary.com/v1_1/dyjrvtift

  #   restart: "always"
