version: "3" # version 3 of docker compose file format
services: # Nests containers under the services field
  vaus-auth-db:
    image: mongo:latest
    container_name: vaus-auth-db
    ports:
      - "4000:27017" # Port mapping like `-p` (Maps port 80 to 4000)
    restart: always

  vaus-auth: # Configures our video streaming microservice
    image: vaus-auth # Sets the name of the image
    build: # Below, paramaters for the build are added
      context: ./auth # Set the directory for microservice
      dockerfile: Dockerfile-dev # Sets Dockerfile that builds the image     <- Change to Dockerfile-prod for prod
    env_file:
      - .env

    volumes:
      - /tmp/auth/npm-cache:/root/.npm:z
      - ./auth/src:/usr/src/app/src:z

    container_name: vaus-auth # Names the container
    ports:
      - "4001:80" # Port mapping like `-p` (Maps port 80 to 4000)
    environment:
      - PORT=80
      - AUTH_DBHOST=mongodb://vaus-auth-db:27017
      - AUTH_DBNAME=vaus-auth-db

    depends_on:
      - vaus-auth-db

    restart: "no" #If microservice crashes - don't auto restart

  vaus-video-db:
    image: mongo:latest
    container_name: vaus-video-db
    ports:
      - "4002:27017" # Port mapping like `-p` (Maps port 80 to 4000)
    restart: always

  vaus-video: # Configures our video streaming microservice
    image: vaus-video # Sets the name of the image
    build: # Below, paramaters for the build are added
      context: ./video # Set the directory for microservice
      dockerfile: Dockerfile-dev # Sets Dockerfile that builds the image     <- Change to Dockerfile-prod for prod
    env_file:
      - .env

    volumes:
      - /tmp/video/npm-cache:/root/.npm:z
      - ./video/src:/usr/src/app/src:z

    container_name: vaus-video # Names the container
    ports:
      - "4003:80" # Port mapping like `-p` (Maps port 80 to 4000)
    environment:
      - PORT=80
      - VIDEO_DBHOST=mongodb://vaus-video-db:27017
      - VIDEO_DBNAME=vaus-video-db

    depends_on:
      - vaus-video-db

    restart: "no" #If microservice crashes - don't auto restart

  vaus-client:
    image: vaus-client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./client/.env

    container_name: vaus-client
    ports:
      - "4004:3000"
    environment:
      - REACT_APP_VIDEO_API_BASE_URL=http://localhost:4003/api/v1
      - REACT_APP_CLOUDINARY_ENDPOINT=https://api.cloudinary.com/v1_1/dyjrvtift

    restart: "always"
